name: snipeit
description: A Flutter wrapper for the SnipeIT asset tracking system REST API
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0